# Generated by Django 3.1.1 on 2020-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200930_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_images/book_default.png', upload_to='book_images'),
        ),
    ]
